
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./front-end
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
        - API_URL=http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend